name: ${project.name}
main: wtf.choco.veinminer.VeinMiner
version: ${project.version}
description: ${project.description}
author: 2008Choco
website: https://www.spigotmc.org/resources/12038/
softdepend: [AAC5, AntiAura, Matrix, NoCheatPlus, Spartan, Vault, WorldGuard]
api-version: 1.13

commands:
  veinminer:
    description: The main command for VeinMiner
    usage: /<command> <version|reload|blocklist|toollist|toggle|pattern|mode>
    aliases: [vm]

permissions:
  veinminer.veinmine.*:
    description: Allow the use of VeinMiner for all tool categories
    default: true

  veinminer.reload:
    description: Allow the use of the '/veinminer reload' subcommand
    default: op
  veinminer.toggle:
    description: Allow the use of the '/veinminer toggle' subcommand
    default: true
  veinminer.mode:
    description: Allow the use of the '/veinminer mode' subcommand
    default: true
  veinminer.pattern:
    description: Allow the use of the '/veinminer pattern' subcommand
    default: op
  veinminer.free.*:
    description: Grants a bypass to all VeinMiner debuffs and costs
    default: false
    children:
      veinminer.free.economy: true
      veinminer.free.hunger: true

  veinminer.free.economy:
    description: Grants a bypass to the VeinMiner cost. Only used if a Vault-supported economy is installed and the cost is greater than 0

  veinminer.free.hunger:
    description: Grants a bypass to the VeinMiner hunger debuff. Only used if hunger modifier is greater than 0

  veinminer.blocklist.*:
    description: Allow the use of the '/veinminer blocklist' subcommand
    default: op
    children:
      veinminer.blocklist.add: true
      veinminer.blocklist.remove: true
      veinminer.blocklist.list.*: true

  veinminer.toollist.*:
    description: Allow the use of the '/veinminer toollist' subcommand
    default: op
    children:
      veinminer.toollist.add: true
      veinminer.toollist.remove: true
      veinminer.toollist.list.*: true

  veinminer.blocklist.list.*:
    description: Allow the use of the '/veinminer blocklist list' subcommand
    default: op
    
  veinminer.toollist.list.*:
    description: Allow the use of the '/veinminer toollist list' subcommand
    default: op