name: ${project.name}
main: wtf.choco.veinminer.VeinMiner
version: ${project.version}
description: ${project.description}
author: 2008Choco
softdepend: [NoCheatPlus, AAC, AntiAura, Spartan, Vault]
api-version: 1.13

commands:
  veinminer:
    description: The main command for VeinMiner
    usage: /<command> <version|reload|blocklist|toollist|toggle|pattern>
    aliases: [vm]

permissions:
  veinminer.veinmine.*:
    description: Allow the use of VeinMiner for all tool categories
    default: true

  veinminer.reload:
    description: Allow the use of the '/veinminer reload' subcommand
    default: op
  veinminer.toggle:
    description: Allow the use of the '/veinminer toggle' subcommand
    default: true
  veinminer.pattern:
    description: Allow the use of the '/veinminer pattern' subcommand
    default: true
  veinminer.free:
    description: Grants a bypass to the VeinMiner cost (only used if a Vault-supported Economy is installed and the cost is greater than 0)
    default: false

  veinminer.blocklist.*:
    description: Allow the use of the '/veinminer blocklist' subcommand
    default: op
    children:
      veinminer.blocklist.add: true
      veinminer.blocklist.remove: true
      veinminer.blocklist.list.*: true

  veinminer.toollist.*:
    description: Allow the use of the '/veinminer toollist' subcommand
    default: op
    children:
      veinminer.toollist.add: true
      veinminer.toollist.remove: true
      veinminer.toollist.list.*: true

  veinminer.blocklist.list.*:
    description: Allow the use of the '/veinminer blocklist list' subcommand
    default: op
    
  veinminer.toollist.list.*:
    description: Allow the use of the '/veinminer toollist list' subcommand
    default: op