name: ${project.name}
main: wtf.choco.veinminer.VeinMiner
version: ${project.version}
description: ${project.description}
author: 2008Choco
softdepend: [NoCheatPlus, AAC, AntiAura]
api-version: 1.13

commands:
  veinminer:
    description: The main command for VeinMiner
    usage: /<command> <version|reload|blocklist|toggle|pattern>
    aliases: [vm]

permissions:
  veinminer.veinmine.*:
    description: Allow the use of VeinMiner for all tool categories
    default: true
    children:
      veinminer.veinmine.pickaxe: true
      veinminer.veinmine.axe: true
      veinminer.veinmine.shovel: true
      veinminer.veinmine.hoe: true
      veinminer.veinmine.shears: true
      veinminer.veinmine.hand: true

  veinminer.reload:
    description: Allow the use of the '/veinminer reload' subcommand
    default: op
  veinminer.toggle:
    description: Allow the use of the '/veinminer toggle' subcommand
    default: true
  veinminer.pattern:
    description: Allow the use of the '/veinminer pattern' subcommand
    default: true

  veinminer.blocklist.*:
    description: Allow the use of the '/veinminer blocklist' subcommand
    default: op
    children:
      veinminer.blocklist.add: true
      veinminer.blocklist.remove: true
      veinminer.blocklist.list.*: true

  veinminer.blocklist.list.*:
    description: Allow the use of the '/veinminer blocklist list' subcommand
    default: op
    children:
      veinminer.blocklist.list.pickaxe: true
      veinminer.blocklist.list.axe: true
      veinminer.blocklist.list.shovel: true
      veinminer.blocklist.list.hoe: true
      veinminer.blocklist.list.shears: true
      veinminer.blocklist.list.hand: true