# To custom categories or to edit the block lists, see the categories.yml

MetricsEnabled: true
PerformUpdateChecks: true

DefaultActivationStrategy: SNEAK
DefaultVeinMiningPattern: 'veinminer:default'
CollectItemsAtSource: true
CollectExperienceAtSource: true
OnlyDamageOnFirstBlock: false
NerfMcMMO: false
Jobs:
  NerfExpGain: false
  NerfCurrencyGain: false

# "RepairFriendly", "RepairFriendlyDurability", "MaxVeinSize", "Cost", and "DisabledWorlds"
# may be defined per-category in the categories.yml file
RepairFriendly: false
RepairFriendlyDurability: 1
MaxVeinSize: 64
Cost: 0.0
DisabledWorlds:
- WorldName

DisabledGameModes:
- CREATIVE
- SPECTATOR

Hunger:
  HungerModifier: 2.5
  MinimumFoodLevel: 1

Client:
  AllowActivationKeybind: true
  AllowPatternSwitchingKeybind: true
  AllowWireframeRendering: true

# VeinMiner supports 3 different types of storage (SQLite is used by default)
#   JSON: Each player's data is stored in its own JSON file under the specified directory. Creates lots of files, is very messy, and is generally discouraged.
#   SQLite: Player data is stored in an SQLite database table. A flat file database. Generally faster and more compact than JSON.
#   MySQL: Player data is stored remotely in a MySQL-compliant database (MySQL, MariaDB, etc.). Use this if you want to share VeinMiner data on multiple servers and have a MySQL server available to use.
Storage:
  # Can be either "JSON", "SQLite", or "MySQL"
  Type: 'SQLite'

  JSON:
    Directory: '%plugin%/playerdata/'

  MySQL:
    Host: 'localhost'
    Port: 3306
    Username: 'username'
    Password: 'password'
    Database: 'veinminer'
    TablePrefix: 'veinminer_'

Aliases:
  acacia_wood:
  - 'minecraft:acacia_log'
  - 'minecraft:acacia_wood'
  birch_wood:
  - 'minecraft:birch_log'
  - 'minecraft:birch_wood'
  cave_vines:
  - 'minecraft:cave_vines'
  - 'minecraft:cave_vines_plant'
  cherry_wood:
  - 'minecraft:cherry_log'
  - 'minecraft:cherry_wood'
  crimson_wood:
  - 'minecraft:crimson_hyphae'
  - 'minecraft:crimson_stem'
  dark_oak_wood:
  - 'minecraft:dark_oak_log'
  - 'minecraft:dark_oak_wood'
  grass_foliage:
  - 'minecraft:bush'
  - 'minecraft:fern'
  - 'minecraft:firefly_bush'
  - 'minecraft:short_dry_grass'
  - 'minecraft:short_grass'
  - 'minecraft:tall_dry_grass'
  - 'minecraft:tall_grass'
  jungle_wood:
  - 'minecraft:jungle_log'
  - 'minecraft:jungle_wood'
  mangrove_wood:
  - 'minecraft:mangrove_log'
  - 'minecraft:mangrove_wood'
  mushroom_blocks:
  - 'minecraft:brown_mushroom_block'
  - 'minecraft:red_mushroom_block'
  oak_wood:
  - 'minecraft:oak_log'
  - 'minecraft:oak_wood'
  pale_oak_wood:
  - 'minecraft:pale_oak_log'
  - 'minecraft:pale_oak_wood'
  poplar_wood:
  - 'minecraft:poplar_log'
  - 'minecraft:poplar_wood'
  pumpkins:
  - 'minecraft:carved_pumpkin'
  - 'minecraft:pumpkin'
  spruce_wood:
  - 'minecraft:spruce_log'
  - 'minecraft:spruce_wood'
  stripped_acacia_wood:
  - 'minecraft:stripped_acacia_log'
  - 'minecraft:stripped_acacia_wood'
  stripped_birch_wood:
  - 'minecraft:stripped_birch_log'
  - 'minecraft:stripped_birch_wood'
  stripped_cherry_wood:
  - 'minecraft:stripped_cherry_log'
  - 'minecraft:stripped_cherry_wood'
  stripped_crimson_wood:
  - 'minecraft:stripped_crimson_hyphae'
  - 'minecraft:stripped_crimson_stem'
  stripped_dark_oak_wood:
  - 'minecraft:stripped_dark_oak_log'
  - 'minecraft:stripped_dark_oak_wood'
  stripped_jungle_wood:
  - 'minecraft:stripped_jungle_log'
  - 'minecraft:stripped_jungle_wood'
  stripped_mangrove_wood:
  - 'minecraft:stripped_mangrove_log'
  - 'minecraft:stripped_mangrove_wood'
  stripped_oak_wood:
  - 'minecraft:stripped_oak_log'
  - 'minecraft:stripped_oak_wood'
  stripped_pale_oak_wood:
  - 'minecraft:stripped_pale_oak_log'
  - 'minecraft:stripped_pale_oak_wood'
  stripped_poplar_wood:
  - 'minecraft:stripped_poplar_log'
  - 'minecraft:stripped_poplar_wood'
  stripped_spruce_wood:
  - 'minecraft:stripped_spruce_log'
  - 'minecraft:stripped_spruce_wood'
  stripped_warped_wood:
  - 'minecraft:stripped_warped_hyphae'
  - 'minecraft:stripped_warped_stem'
  warped_wood:
  - 'minecraft:warped_hyphae'
  - 'minecraft:warped_stem'
