name: VeinMiner
main: wtf.choco.veinminer.VeinMinerPlugin
version: '@project.version@'
description: Mine multiple blocks of the same type in quick succession.
author: Choco
website: https://www.spigotmc.org/resources/12038
softdepend: [ AAC5, AntiAura, LightAntiCheat, Matrix, NoCheatPlus, Spartan, Vault, WorldGuard, mcMMO, PlaceholderAPI ]
api-version: 1.17

commands:
  veinminer:
    description: The main command for VeinMiner
    usage: /<command> <version|reload|blocklist|toollist|toggle|pattern|mode>
    aliases: [vm]
  blocklist:
    description: Edit the block lists of vein mining categories
    permission: veinminer.command.blocklist
    usage: /<command> <category> <add|remove|list> [state]
  toollist:
    description: Edit the tool lists of vein mining categories
    permission: veinminer.command.toollist
    usage: /<command> <category> <add|remove|list> [item]

permissions:
  veinminer.veinmine.*:
    description: Allow the use of vein miner for all tool categories
    default: true
  veinminer.free.*:
    description: Grants a bypass to all VeinMiner debuffs and costs
    default: false
    children:
      veinminer.free.economy: true
      veinminer.free.hunger: true

  veinminer.free.economy:
    description: Grants a bypass to the vein miner cost. Only used if a Vault-supported economy is installed and the cost is greater than 0

  veinminer.free.hunger:
    description: Grants a bypass to the vein miner hunger debuff. Only used if hunger modifier is greater than 0

  veinminer.command.reload:
    description: Allow the use of the '/veinminer reload' subcommand
    default: op
  veinminer.command.blocklist:
    description: Allow the use of the '/blocklist' command
    default: op
  veinminer.command.toollist:
    description: Allow the use of the '/toollist' command
    default: op
  veinminer.command.toggle:
    description: Allow the use of the '/veinminer toggle' subcommand
    default: true
  veinminer.command.mode:
    description: Allow the use of the '/veinminer mode' subcommand
    default: true
  veinminer.command.pattern:
    description: Allow the use of the '/veinminer pattern' subcommand
    default: true
