# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle Publish

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Publish to repository
      run: ./gradlew publish
      env:
        ORG_GRADLE_PROJECT_mavenUsername: ${{ secrets.REPOSITORY_USERNAME }}
        ORG_GRADLE_PROJECT_mavenAccessToken: ${{ secrets.REPOSITORY_TOKEN }}
