# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle Build, Test, and Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 16 # veinminer-bukkit compiles against Java 16
      uses: actions/setup-java@v3
      with:
        java-version: 16
        distribution: 'temurin'
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build VeinMiner-Bukkit with Gradle
      run: ./gradlew :VeinMiner-Bukkit:build
      env:
        ORG_GRADLE_PROJECT_mavenUsername: ${{ secrets.REPOSITORY_USERNAME }}
        ORG_GRADLE_PROJECT_mavenAccessToken: ${{ secrets.REPOSITORY_TOKEN }}
    - name: Check(style) VeinMiner-Fabric with Gradle
      run: ./gradlew :VeinMiner-Fabric:check
      env:
        ORG_GRADLE_PROJECT_mavenUsername: ${{ secrets.REPOSITORY_USERNAME }}
        ORG_GRADLE_PROJECT_mavenAccessToken: ${{ secrets.REPOSITORY_TOKEN }}
